name: Pipeline con Nginx

on:

  push:

  paths:
  - ../frontend/index.html
  - ../frontend/Dockerfile

  branches:
  - main
  

jobs:

  build and deploy:
   runs on: self-hosted

   steps:
   - name: Checkout del codigo
     uses: actions/checkout@v3

   - name: Iniciar sesión en Docker Hub
     run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

   - name: Construir la imagen
     run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ../public
   
   - name: Subir la imagen a Docker Hub
     run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

   - name: Detener y eliminar el contenedor anterior
     run: |
           docker stop nginx_server || true
           docker rm nginx_server || true

   - name: Construir y ejecutar el nuevo contenedor
     run: |
           docker build -t nginx_image ../public
           docker run -d --name nginx_server -p 8080:80 nginx_image